language: node_js

node_js:
 - 14

install:
  - npm install nyc
  - npm install coveralls
  - npm install esm

script:
  - npm run coverage

after_script:
  - npm run coveralls

deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: 'villeoonatestiraportti'
  skip_cleanup: true

addons:
  artifacts:
    s3_region: eu-central-1
    debug: true
    paths:
      - ./tests/_output
      - $(git ls-files -o | tr "\n" ":")
      - $(ls /var/log/*.log | tr "\n" ":")
      - $HOME/some/other/thing.log
    target_pahts: $TRAVIS_BUILD_NUMBER

  